import Nav from './Nav';
import styles from './layout.module.scss';
import Head from 'next/head';

export default function Layout(props) {
  return (
    <div className={styles.layout}>
      <Head>
        <title>Taipei Zoo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'
        />
      </Head>

      <Nav />

      <main className={styles.main}>{props.children}</main>
    </div>
  );
}
